[package]
name = "levante-admin"
version = "0.1.0"
authors = ["Crazz <mhxdev@gmail.com>"]

[dependencies]
env_logger = "0.6"
actix = "0.7.9"
actix-web = "0.7.9"
diesel = { version = "^1.4.1", features = ["mysql", "r2d2","chrono"] }
futures = "0.1.25"
uuid = { version = "0.7.2", features = ["serde", "v4"] }
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
chrono = "0.4.6"